apiVersion: v1
data:
  config.yaml:
{{ toYaml .Values.config | indent 4 }}
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
