apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: web
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
{{- if .Values.ingress.tls.secret }}
    secretName: {{ .Values.ingress.tls.secret }}
{{ else }}
    secretName: {{ template "fullname" . }}
{{- end }}
{{- end }}
