apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "dc.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "dc.name" . }}
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: storage-cleanup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            args:
            - /storage
{{- range .Values.slugs -}}
            - {{ . | quote }}
{{- end }}
{{- if .Values.env }}
            env:
{{ toYaml .Values.env | indent 12 }}
{{- end }}
          restartPolicy: OnFailure
