apiVersion: v1
data:
{{ toYaml .Values.configFiles | indent 2 }}
kind: ConfigMap
metadata:
  name: {{ template "microservice.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "microservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: microservice
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
